
#!/bin/bash -l



REMOTE_ROOT=$(readlink -f .)
echo 0 > $REMOTE_ROOT/3be88ef818807112756ad2ac63dd42e93b2241e9_flag_if_job_task_fail
test $? -ne 0 && exit 1




export DPDISPATCHER_NUMBER_NODE=1
export DPDISPATCHER_CPU_PER_NODE=1
export DPDISPATCHER_GPU_PER_NODE=0
export DPDISPATCHER_QUEUE_NAME=
export DPDISPATCHER_GROUP_SIZE=1
export DP_AGENT_RUNNING_MODE=1
export SUBMISSION_TIMESTAMP=1745591399.683823



source $REMOTE_ROOT/3be88ef818807112756ad2ac63dd42e93b2241e9.sub.run

cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 3be88ef818807112756ad2ac63dd42e93b2241e9_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 3be88ef818807112756ad2ac63dd42e93b2241e9_job_tag_finished; else exit 1;fi



